name: chfchf0306
on:
  schedule:
    - cron: '31 3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: chfchf0306 
jobs: 
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: chfchf0306
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chfchf0306/jeidian4.18.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
